### PR TITLE
Use prop-types package instead of React's PropTypes

### PR DESCRIPTION
**Pull request by gnapse**
More info about this [here](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes).

### CODE REVIEW

**Comment by monvillalon** [comment]
Thanks for bringing this to my attention and for the pull request, I will be merging this soon, with a minor version bump. Sorry for the long wait

**Comment by jameswyse** [comment]
@monvillalon bump!

**Comment by raftalks** [comment]
looking forward to this update

**Comment by gnapse** [comment]
@monvillalon any updates on when this can be merged?

**Comment by monvillalon** [comment]
@gnapse @raftalks @jameswyse 
Merged sorry for the delay and thanks for waiting.

**Comment by monvillalon** [comment]
@gnapse After thinking about it, I think an additional step I should do is to remove the prop-types via babel using [babel-plugin-react-remove-prop-types](https://github.com/nkt/babel-plugin-react-remove-prop-types). And adding **prop-types** to devDependecies so that they are not bundled with the library at all.  In any case I plan to release this as soon as I can squeeze some time for it.

**Comment by gnapse** [comment]
@monvillalon sounds like a good idea. I had not thought about that.

**Pull request merged**
